In [18]:
import pandas as pd
import numpy as np

# data imports
df = pd.read_csv("data/listings/raw")
df.head()

,advertiser-role,available,days-old,id,link,neighbourhood,price,property-type,rooms-in-property,status,title
0,live out landlord,Available Now,1,2874990,/flatshare/fad_click.pl?fad_id=2874990&search_...,Aldgate,¬£650pcm,flat,3,new,AVOID TUBE - Aldgate Zone 1 - Walk to Office
1,agent,Available Now,0,12741853,/flatshare/flatshare_detail.pl?flatshare_id=12...,Hoxton,\n¬£650pcm,flat,5,boosted,Nice single Rm in modern Flat - Hoxton/Shoreditch
2,agent,Available Now,0,15039631,/flatshare/flatshare_detail.pl?flatshare_id=15...,London SW3,¬£400pcm,flat,4,new today,üî∑Classy Double Room in Chelsea areaüî∑
3,agent,Available Now,0,14138806,/flatshare/flatshare_detail.pl?flatshare_id=14...,Hoxton,\n¬£400pcm,flat,5,boosted,Modern Double in new-built Flat - Hoxton/Shore...
4,agent,Available Now,0,15039616,/flatshare/flatshare_detail.pl?flatshare_id=15...,London W8,"¬£870- ¬£1,050pcm",flat,5,new today,üè¢Special Double Room in Kensington areaüè¢

In [37]:
# Clean up price column and split in weekly and monthly rent
raw_prices = df.price.values
cleanPriceStrings = []

for raw_price in raw_prices:
    
    cleaned_string = raw_price
    
    # Remove redundent symbols
    cleaned_string = cleaned_string.replace("\n","")
    cleaned_string = cleaned_string.replace("¬£","")
    cleaned_string = cleaned_string.replace(" ","")
    cleaned_string = cleaned_string.replace(",","")
    
    # fix standardise into pcm if pw
    if ("pw" in cleaned_string):
        stringComps = cleaned_string.split("pw")
        if "-" in stringComps[0]: 
            priceRange = stringComps[0].split("-")
            priceRange = [float(price)*4 for price in priceRange
            low, high = priceRange
        else:
            low, high = [stringComps[0], stringComps[0]]
              
    # sort range 
    elif ("pcm" in cleaned_string):
        stringComps = cleaned_string.split("pcm")
        if "-" in stringComps[0]: 
            priceRange = stringComps[0].split("-")
            low, high = [float(price) for price in priceRange]
        else:
            low, high = [float(stringComps[0]),float(stringComps[0])]

    cleanedPrice = {
        "low": low,
        "high": high
    }
        
    # append
    cleanPriceStrings.append(cleanedPrice)

# Get range into "low", "high" 

print(cleanPriceStrings[0:50])

ValueError: not enough values to unpack (expected 2, got 1)